# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mount the backend directory
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      PYTHONUNBUFFERED: 1

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://backend:8000 

volumes:
  db-data: